#!/bin/sh

export ACCESS_TOKEN=yJhbGciOiJSUzI1NiIsImtpZCI6IjMxNjEiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE3NjQ5NjE4ODMsImlzcyI6InNvbG8uaW8iLCJvcmciOiJzb2xvLmlvIiwic3ViIjoiY2Fyb2wiLCJ0ZWFtIjoiZGV2In0.gkoQb47o3MBb2asSnofz9V15zlI0okttw2Bd9c4SLOWHDOEt6lxP-qFpDRXyQgBvvtNdNpfaZ0-h5JtIZ3AyCTg2R0Lxnivm6U2VIoZHFB5whODk_RiyX2XX3NFCfYI3g5wMp0J9sOCiG3_KauwznvzQWrIJqmdTbbSIfdQmMviyCg9WTEsbZacK1_reCw5pmqAI6YwVHFyvOrt4megmCaaLH_xlGRllmOZRsrF0eFSyHI1LreTgq13uIzPtgZjFDHKehRPbxtrkAOKH-O3XP-C0a27anBgmBvCOjccQ7AEhYpDBH8ReGjpdjiyEvgRuzGQCUN-t3hVNQEwt4PWXKA

curl -v -H "Authorization: Bearer $ACCESS_TOKEN" http://api.example.com/get


